#!/usr/bin/php
<?
$plugin = "unassigned.devices";
require_once("/usr/local/emhttp/plugins/${plugin}/include/lib.php");

# Run in the background
if (!in_array("--bg", $argv)) {
  exec(implode(" ", $argv)." --bg 1>/dev/null 2>&1 &");
  exit(0);
}

$DEVNAME = (isset($_ENV['DEVNAME'])) ? $_ENV['DEVNAME'] : ( isset($argv[1]) ? $argv[1] : NULL );
$DEVNAME = (file_exists($DEVNAME)) ? realpath($DEVNAME) : $DEVNAME;
if (! $DEVNAME) die("Fail: disk device not informed.\n");

# Mount SMB shares
if (strpos($DEVNAME, "//") === 0 || $DEVNAME == "all") {
  foreach (get_samba_mounts() as $info) {
    $device = $info['device'];
    if ( preg_match("#".$DEVNAME."#i", $device) || $DEVNAME == "all" ) {
      if (! $info['automount'] && $DEVNAME == "all" ) {
        debug("SMB mount '${info[device]}' auto mount is disabled, aborting.");
        continue;
      }
      debug("Drive found with the following attributes: ".(implode(', ', array_map(function ($v, $k) { return "$k='$v'"; }, $info, array_keys($info)))));
      debug("Adding disk $drive ...");
      if (do_mount( $info )) {
        touch("/var/state/${plugin}");
        execute_script($info, "ADD");
      }
    }
  }
}

# Mount local disks
foreach(get_unasigned_disks() as $name => $disk) {
  $device = $disk['device'];
  foreach ($disk['partitions'] as $partition) {
    if ( preg_match("#".$DEVNAME."#i", realpath($partition)) || $DEVNAME == "all" ) {
      debug("");
      $info = get_partition_info($partition,true);
      if (! $info['automount'] && ( $DEVNAME == "all" || isset($_ENV['DEVNAME']) )) {
        debug("Disk with serial '${info[serial]}' auto mount is disabled, aborting.");
        continue;
      }
      debug("Drive found with the following attributes: ".(implode(', ', array_map(function ($v, $k) { return "$k='$v'"; }, $info, array_keys($info)))));
      debug("Adding disk $drive ...");
      if (do_mount( $info )) {
        touch("/var/state/${plugin}");
        if (config_shared( $info['serial'],  $info['part'])) {
          add_smb_share($info['mountpoint'], $info['label']);
        } else {
          debug("Partition '{$info[label]}' marked as not sharable, skipping.");
        }
        execute_script($info, "ADD");
        setSleepTime($device);
      }
      debug("Disk ${info[label]} shared successfully.");
    }
  }
}
touch("/var/state/${plugin}");
?>
