#!/usr/bin/php -q
<?PHP
/* Copyright 2005-2018, Lime Technology
 * Copyright 2012-2018, Bergware International.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 */
function disable_ob() {
    // Turn off output buffering
    ini_set('output_buffering', 'off');
    // Turn off PHP output compression
    ini_set('zlib.output_compression', false);
    // Implicitly flush the buffer(s)
    ini_set('implicit_flush', true);
    ob_implicit_flush(true);
    // Clear, and turn off output buffering
    while (ob_get_level() > 0) {
        // Get the curent level
        $level = ob_get_level();
        // End the buffering
        ob_end_clean();
        // If the current level has not changed, abort
        if (ob_get_level() == $level) break;
    }
    // Disable apache output buffering/compression
    if (function_exists('apache_setenv')) {
        apache_setenv('no-gzip', '1');
        apache_setenv('dont-vary', '1');
    }
}
disable_ob();
?>
<p style='text-align:center'><span class='error label'>Error</span><span class='warn label'>Warning</span><span class='system label'>System</span><span class='array label'>Array</span><span class='login label'>Login</span></p>
<p style='text-align:center'><button onclick="window.location = '/plugins/preclear.disk/Preclear.php?action=get_log&session=<?=$argv[1];?>'">Download</button></p>
<?
$docroot = $docroot ?? $_SERVER['DOCUMENT_ROOT'] ?: '/usr/local/emhttp';
require_once "$docroot/webGui/include/ColorCoding.php";

$serial = (isset($argv[1])) ? $argv[1] : false;

$handle = popen('/usr/bin/tail -n +1 -f "/var/log/preclear.disk.log" 2>&1', 'r');
while (!feof($handle)) {
  $line = fgets($handle);
  if (strpos($line,'tail_log')!==false) continue;
  if ($serial && strpos($line, $serial)==false) continue;
  $span = "span";
  foreach ($match as $type) foreach ($type['text'] as $text) if (preg_match("/$text/i",$line)) {$span = "span class='{$type['class']}'"; break 2;}
  $line = preg_replace("/ /i", "&nbsp;", htmlspecialchars($line));
  echo "<$span>".$line."</span>";
  flush();ob_flush();
}
pclose($handle);
?>