#!/bin/bash

for disk in $(find /tmp/.preclear/ -mindepth 1 -maxdepth 1 -type d -exec basename '{}' \;); do
  case "$1" in
    array_started|stopping_svcs)
      echo "Pausing preclear of disk '$disk'"|logger -t preclear.disk
      touch "/tmp/.preclear/${disk}/pause"
    ;;
    started|stopped)
      echo "Resuming preclear of disk '$disk'"|logger -t preclear.disk
      rm -f "/tmp/.preclear/${disk}/pause"
    ;;
  esac
done