#!/usr/bin/php
<?
$plugin = "gfjardim.usb.automount";
require_once("/usr/local/emhttp/plugins/${plugin}/include/usb_mount_lib.php");
$PRESENT=array();

$DEVNAME = (isset($_ENV['DEVNAME'])) ? $_ENV['DEVNAME'] : ( isset($argv[1]) ? $argv[1] : NULL );
foreach(get_unasigned_disks() as $disk) {
  $device = $disk['device'];
  $PRESENT[] = $device;
  foreach ($disk['partitions'] as $partition) {
    if ( preg_match("#".$DEVNAME."#i", realpath($partition)) || $DEVNAME == "all" ) {
      $info = get_partition_info($partition);
      debug("\nDrive found with the following attributes: ".(implode(', ', array_map(function ($v, $k) { return "$k='$v'"; }, $info, array_keys($info)))));
      if ( is_mounted($info['device']) ) {
        debug("Removing disk ${info[label]} share ...");
        execute_script($info, "REMOVE");
        if ( rm_smb_share($info['target'], $info['label']) ) {
          debug("Unmounting disk ${info[label]} ..");
          if ( do_unmount($info['device'], $info['mountpoint']) ) {
            debug("Disk ${info[label]} removed successfully.");
          }
        }
      }
    }
  }
}
touch("/var/state/${plugin}");
?>