#!/usr/bin/php
<?
$plugin = "gfjardim.usb.automount";
require_once("/usr/local/emhttp/plugins/${plugin}/include/usb_mount_lib.php");

$DEVNAME = (isset($_ENV['DEVNAME'])) ? $_ENV['DEVNAME'] : ( isset($argv[1]) ? $argv[1] : NULL );
foreach(get_usb_disks() as $disk) {
  if ( $DEVNAME == realpath($disk) || $DEVNAME == "all" ) {
    $info = get_partition_info($disk);
    if (! is_automount($info['serial']) && ( $DEVNAME == "all" || isset($_ENV['DEVNAME']) )) {
      debug("Disk with serial '${info[serial]}' auto mount is disabled, aborting.");
      continue;
    }
    debug("Drive found with the following attributes: ".(implode(', ', array_map(function ($v, $k) { return "$k='$v'"; }, $info, array_keys($info)))));
    debug("Adding disk $drive ...");
    if (do_mount($info['device'], $info['mountpoint'], $info['fstype'] )) {
      add_smb_share($info['mountpoint'], $info['label']);
      execute_script($info, "ADD");
    }
    debug("Disk ${info[label]} shared successfully.");
  }
}
touch("/var/state/${plugin}");
?>
