#!/usr/bin/php
<?
$plugin = "gfjardim.usb.automount";
require_once("/usr/local/emhttp/plugins/${plugin}/include/usb_mount_lib.php");

$DEVNAME = (isset($_ENV['DEVNAME'])) ? $_ENV['DEVNAME'] : ( isset($argv[1]) ? $argv[1] : NULL );
foreach(get_usb_disks() as $disk) {
  if ( $DEVNAME == realpath($disk) ) {
    $info = get_partition_info($disk);
    debug("Drive found with the following attributes: ".(implode(', ', array_map(function ($v, $k) { return "$k='$v'"; }, $info, array_keys($info)))));
    debug("Removing disk ${info[label]} share ...");
    if ( is_mounted($info['device']) ) {
      execute_script($info, "REMOVE");
      if ( rm_smb_share($info['mountpoint'], $info['label']) ) {
        debug("Unmounting disk ${info[label]} ..");
        if ( do_unmount($info['device'], $info['mountpoint']) ) {
          debug("Disk ${info[label]} removed successfully.");
        }
      }
    }
  }
}
touch("/var/state/${plugin}");
?>