#!/usr/bin/php
<?
$plugin = "gfjardim.usb.automount";
require_once("/usr/local/emhttp/plugins/${plugin}/include/usb_mount_lib.php");

if (isset($_ENV['DEVLINKS'])) {
  foreach (explode(" ", $_ENV['DEVLINKS']) as $link) {
    get_udev_info($link, $_ENV);
  }
}
touch("/var/state/${plugin}");
?>