#!/bin/bash
for disk in $(find /tmp/.preclear/ -mindepth 1 -maxdepth 1 -type d |xargs basename); do
  echo "Resuming preclear of disk '$disk'"|logger -t preclear.disk
  rm -f "/tmp/.preclear/${disk}/pause"
done